server:
  port: 8080

logging:
  level:
    root:
    org.hibernate.orm: ERROR

spring:
  datasource:
    url: jdbc:mysql://:3306/mydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  server:
    servlet:
      session:
        timeout: 1800


